// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResuleCode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ResuleCode.proto</summary>
public static partial class ResuleCodeReflection {

  #region Descriptor
  /// <summary>File descriptor for ResuleCode.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResuleCodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBSZXN1bGVDb2RlLnByb3RvKjAKClJlc3VsZUNvZGUSCAoETm9uZRAAEgwK",
          "CEZpbmlzaGVkEAESCgoGRmFpbGVkEAJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResuleCode), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 协议号枚举
/// </summary>
public enum ResuleCode {
  [pbr::OriginalName("None")] None = 0,
  /// <summary>
  ///完成的
  /// </summary>
  [pbr::OriginalName("Finished")] Finished = 1,
  /// <summary>
  ///失败的
  /// </summary>
  [pbr::OriginalName("Failed")] Failed = 2,
}

#endregion


#endregion Designer generated code
