// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MessageType.proto</summary>
public static partial class MessageTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for MessageType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFNZXNzYWdlVHlwZS5wcm90byo7CgtNZXNzYWdlVHlwZRIICgROb25lEAAS",
          "EAoKQ1NMb2dpblJlcRCpjD0SEAoKU0NMb2dpblJlcxDpkHpiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageType), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// 协议号枚举
/// </summary>
public enum MessageType {
  [pbr::OriginalName("None")] None = 0,
  [pbr::OriginalName("CSLoginReq")] CsloginReq = 1001001,
  [pbr::OriginalName("SCLoginRes")] ScloginRes = 2001001,
}

#endregion


#endregion Designer generated code
